# Your Solution
version: '3'
services:

  book-catalog:
    image: book-catalog:latest
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book-catalog
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_URL=postgresql://book_library_db_user:SYdFunimpuitgtV6fG5HtbhP46blMxOL@dpg-crnm0l68ii6s73etflpg-a.oregon-postgres.render.com/book_library_db
    restart: "no"

  inventory-management:
    image: inventory-management:latest
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory-management
    ports:
      - "8081:8081"
    environment:
      - PORT=8081
      - DATABASE_URL=postgresql://book_library_db_user:SYdFunimpuitgtV6fG5HtbhP46blMxOL@dpg-crnm0l68ii6s73etflpg-a.oregon-postgres.render.com/book_library_db
    restart: "no"
